### ISSUE TITLE
Thesis Availability

### ISSUE THREAD

**Issue by chnanc001** [davircarvalho/Individualized_HRTF_Synthesis#2]
Hi

I was wondering would if it is possible for you to share your thesis?  I am particularly interested in if you did any verification and the results of any evaluations performed.

**Comment by davircarvalho** [comment]
Hello,

here you can find the link for the thesis: https://drive.google.com/file/d/1JVDNxQreYzg7jfauMwFnK3Sg21aB5ri5/view?usp=sharing

I did an analysis comparing the performance of this model against the Fabian and the Kemar DTFs regarding spectral distortion. This model consistently outperformed the generic DTFs in all the tests. 

Although the document is written in portuguese there are a lot of pictures, I hope that's helpful. The subjective tests were done after the thesis, and haven't been published yet.

Cheers!
