### ISSUE TITLE
[Feature request] Standalone executable/installer

### ISSUE THREAD

**Issue by ThreeDeeJay** [davircarvalho/Individualized_HRTF_Synthesis#5]
Hi, I've been a big fan of this app for a while, but when I recommend it to other people, they usually give up because they find it too difficult to download, activate and/or install MATLAB or the HRTF app.
According to [this post](https://sourceforge.net/p/hesuvi/discussion/general/thread/df9b0f231c/?limit=25#4bbb/9330), MATLAB can generate a standalone installer (which even downloads the runtime automatically) but apparently there was something wrong with that particular compilation because it got stuck generating HRTFs for some people.
So it would be really nice if there was an official, recent and working standalone installer so installing and running the app is straightforward for people who aren't tech savvy.

**Comment by davircarvalho** [comment]
Fair enough, I'll make that happen

**Comment by davircarvalho** [comment]
The issue will be closed due to release [tag 2.10.02](https://github.com/davircarvalho/Individualized_HRTF_Synthesis/releases/tag/2.10.02).

**Comment by ThreeDeeJay** [comment]
Thank you so much!
I can confirm it works flawlessly on my end 👍
