### ISSUE TITLE
Multiple azimuth responses on the +90/-90 degree elevation

### ISSUE THREAD

**Issue by ThreeDeeJay** [davircarvalho/Individualized_HRTF_Synthesis#8]
Hello there, me again
So, turns out that even after https://github.com/davircarvalho/Individualized_HRTF_Synthesis/issues/7, I'm afraid I've run into another issue when attempting to convert EAC SOFAs to OpenAL Soft MHR format, which I reported to the OpenAL Soft developer and got this response: https://github.com/kcat/openal-soft/issues/779#issuecomment-1294216909:

> The `Non-singular poles on field distance ...` error means there's multiple azimuth responses on the +90 (or -90) degree elevation, which makes no sense to have since every azimuth at the +/-90 degree elevation is the same position. `makemhr` has no idea what to do with them when there's more than one, as there should only be one.
> 
> The `Too many missing elevations` error means the detected elevation step doesn't use any elevations below 0 degrees, which means `makemhr` can't synthesize any missing lower elevations to fit that stepping value. I'll need to take a look at the SOFA to see why it may be doing that; the elevation step detection can misjudge things since it needs to find a stepping value that has responses on each elevation step, while also expecting lower elevations to not exist (which will be synthesized later as needed).
> 
> The `_Netcdf4Coordinates = <null>` warnings are just saying it found an attribute it's unfamiliar with. As long as such an attribute is unrelated to interpreting the data, it's harmless.

Here are the SOFA files and script to replicate said errors so you can confirm on your end: https://www.dropbox.com/s/8aihxjgb5f6kebt/makemhr_script%2BEAC%2BMesh2HRTF_SOFAs.7z?dl=1

**Comment by Fritomaster** [comment]
Would love a fix for this so we can convert to .mhr

**Comment by davircarvalho** [comment]
Hey guys I've been on holidays last month, I will investigate this

**Comment by ThreeDeeJay** [comment]
Just tested 05ac8cc0cdc01d09ff022c0d3c075b49638c86a5 with the [latest](https://github.com/kcat/openal-soft/releases/download/makemhr/makemhr.zip) and previous makemhr in my [test package](https://www.dropbox.com/s/8aihxjgb5f6kebt/makemhr_script%2BEAC%2BMesh2HRTF_SOFAs.7z?dl=1), and the good news is that the `Non-singular poles` error is gone, but the bad news is that I'm getting a more generic error: `Invalid format`
![image](https://user-images.githubusercontent.com/71472458/206929084-18fce252-dde8-4036-ac9e-83b146e952ce.png)
It may be an issue in makemhr's end so I guess I'll report it back in the OpenAL Soft repo.

**Comment by ThreeDeeJay** [comment]
Ok so since the new problem seems to be related to libmysofa, I'm gonna go ahead and close this issue since it's been fixed 👍
