### ISSUE TITLE
Question: About Room Simulation

### ISSUE THREAD

**Issue by Fritomaster** [davircarvalho/Individualized_HRTF_Synthesis#9]
Sorry not sure where to post this, but now that I have one generated is there a way to take something like this and give it the depth of a room? So I can get the feeling of listening to speakers in a room?

**Comment by ThreeDeeJay** [comment]
If we could convert them to MHR, we could use Crystal Mixer which uses OpenAL Soft and set/customize an EAX/EFX preset for different room types. But it requires fixing https://github.com/davircarvalho/Individualized_HRTF_Synthesis/issues/8
Alternatively, if you just wanna test individual sounds with your HRTF, you might be able to use it with [Anaglyph VST](http://anaglyph.dalembert.upmc.fr/) in a DAW, which can spatialize audio tracks using your SOFAs (though not sure if EAC's work) and a separate, optional "Studio" which I think is a BRIR SOFA that you might be able to replace with other ones you find on the internet.
![image](https://user-images.githubusercontent.com/71472458/206553427-23cbcaf7-34e8-4533-8412-cb51421503c4.png)
I think the SOFAs go in the (data?) folder that's next to the DLL where you install Anaglyph.

**Comment by Fritomaster** [comment]
Awesome. Appreciate the write up. I'll have to see if EAC's works.

**Comment by Fritomaster** [comment]
> If we could convert them to MHR, we could use Crystal Mixer which uses OpenAL Soft and set/customize an EAX/EFX preset for different room types. But it requires fixing #8 Alternatively, if you just wanna test individual sounds with your HRTF, you might be able to use it with [Anaglyph VST](http://anaglyph.dalembert.upmc.fr/) in a DAW, which can spatialize audio tracks using your SOFAs (though not sure if EAC's work) and a separate, optional "Studio" which I think is a BRIR SOFA that you might be able to replace with other ones you find on the internet. ![image](https://user-images.githubusercontent.com/71472458/206553427-23cbcaf7-34e8-4533-8412-cb51421503c4.png) I think the SOFAs go in the (data?) folder that's next to the DLL where you install Anaglyph.

Awesome. Appreciate the write up. I'll have to see if EAC's works.

**Comment by davircarvalho** [comment]
these HRTFs won't work straight away with anaglyph, because they require the HRTFs to be in a slightly different format. But I remember they had some preprocessing code in their website they would convert these, please contact them if you can't find the code.
